apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: grant-wp-amoc
  namespace: wordpress
spec:
  mariaDbRef:
    name: mariadb
  privileges:
    # - "SELECT"
    # - "INSERT"
    # - "UPDATE"
    - "ALL PRIVILEGES"
  database: "wp-amoc"
  table: "*"
  username: wp-amoc
  grantOption: true
  host: "%"
  # Delete the resource in the database whenever the CR gets deleted.
  # Alternatively, you can specify Skip in order to omit deletion.
  cleanupPolicy: Delete
  requeueInterval: 10h
  retryInterval: 30s
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: grant-wp-art
  namespace: wordpress
spec:
  mariaDbRef:
    name: mariadb
  privileges:
    # - "SELECT"
    # - "INSERT"
    # - "UPDATE"
    - "ALL PRIVILEGES"
  database: "wp-art"
  table: "*"
  username: wp-art
  grantOption: true
  host: "%"
  # Delete the resource in the database whenever the CR gets deleted.
  # Alternatively, you can specify Skip in order to omit deletion.
  cleanupPolicy: Delete
  requeueInterval: 10h
  retryInterval: 30s
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: grant-wp-hhk
  namespace: wordpress
spec:
  mariaDbRef:
    name: mariadb
  privileges:
    # - "SELECT"
    # - "INSERT"
    # - "UPDATE"
    - "ALL PRIVILEGES"
  database: "wp-hhk"
  table: "*"
  username: wp-hhk
  grantOption: true
  host: "%"
  # Delete the resource in the database whenever the CR gets deleted.
  # Alternatively, you can specify Skip in order to omit deletion.
  cleanupPolicy: Delete
  requeueInterval: 10h
  retryInterval: 30s