---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mariadb
  namespace: wordpress
spec:
  encryptedData:
    password: AgBf9GPWFvTw1V+hXNBwoCHkZnIpVSzkOon+oSRSsT/VhmIONAvrelLSjBbCj+Fjt5I7qzIam/2MrEtYFcbXUuh1BD4YEWi1yj3ws77O7sRQ+x2OE4lfLx3G2iY4e+ykpRN3E0XtNxbVa3+O2KlZi41jpsHOO3ZU7yB4FmUdkr/b8VfX9d4bp1FMccfW35sY+xXW7rpsXkw4DDQ5nGTdqfQZ1OcCzIgh17EKvcZ8d4thmAwZd07ldsYco0KLysROy9UL+cgyXE3cNjE1KAnXTMNf2OgNFTrzqQP4JjGGxJ5jziPL7P+p++aTyqrtLw/8kXw1Iy4SAERBuWbuQ6JIW6ewViWwZbko+btQvK9dcwyZAUvH3vbjoXc7oHvvbjnkpwSGos9hIdDS01oaBZfORtCFGb5srL2osQ+AdrDu+/9m6ghEfBmg4XrkQNPpJxg+WKhjKw5QWKamqGD3WqvsVq8FniUekSHHWDR9HJLNEZX7HM4YY0cmDVRqc/QE9CrRdRKYrSpvb62xMzt1f8mZ/sKfUPkcya/pfVMZzPrFheLfWsD9dD8Fl8zcCzJS1gLOECoQW01ykp6CNwJGCwvV0czARziJOfzASg+BDXDcIH54mwlqUXiUdyT3Rd7AsuWjaoOVa5/STGrT3VUQwOIVZyT4L6UKpfXZsU10zo9gXc+htlo0xSM+UVgIVXusOGgfgmiYYUBLqAhgRWoh9h1hF5XGx64KKuTDfg==
  template:
    metadata:
      creationTimestamp: null
      name: mariadb
      namespace: wordpress
