---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-secret
  namespace: wordpress
spec:
  encryptedData:
    .dockerconfigjson: AgCIqvK6Ifi1LO7MPZ1pHMHFLBktjgPA5BIYU+vAQzTm8RwTufI1Tcup/aDSoUpcjIH3nn6XiNpLHq9oWdz0Lwgvs2kLIIU7cV6/2ewVyqYbP+fA8VsssWDROhF8jA4BtF0plh4CPSN1cgSP/hf8lWAt3Q/Q6UfG+2Q+mD5XBRvVkTuXl1rpLMJE3Xh9c2orR6LTJLqrkncizQ/BMDYHiIvveCTN4sT/O6xT7K/VjAjdRIdOKexxsM7+lCjIUn6EN/YdGbUOmG2xHlBJ6FtdFcUxXTQCB0LtRBUAL3RCYmEZ3YzHxqLTOVwbikRCWV57+uaEO5CAuZyWu00wU5hb1ZfOV3s+raJXWL4phjiADnSMJctclmcuX1FD2nk5IWF23afZsIUYhM+SFre6UqpFeCeT4W6cefD7h0w5GDzA7RfR2pXI79CndxeTQxHmX+NxhB7H8fEFCHQ3ENMdCcYWvhV9vG2NY2jM1CMOULYAcMI+EbY8WqNRqM1I8JB5BZkSV7oGX93zHWwH+MO9ctkiLURJzKJLF3hxTZ966zIKLG2LHRoVYP8d7o/t/1HRmw8/KB2HyCRzqfbBAWaIDSbJ+voyGTaEfqs4kKkQUmFJFT2EXAnw8VILDGdxqvqTs1/ZOPePJ8Xpjd0OBWzx3Unu7FZtNb3d/S9vDdip6aT2DXOhk9Inqv4scpqO5cza7ZbjeSFWdUEmUT41oSDI7K6GrNW/K+B4xpzid9kKL+4h7IE3f9J9oeWV0YTFEJ+ea7MY6NeSf2DUS/ZdLyxbJbwiSDE1YY6EGKKImcl2gIZv5I27nMgeY/ijvcD9VQfC12iAsVWxa3RJBgXw8IoJOQ6fg8WG97S11YIAjeXtGaHijfunjjGfoDABX6uNT+bnX77WqQ==
  template:
    metadata:
      creationTimestamp: null
      name: registry-secret
      namespace: wordpress
    type: kubernetes.io/dockerconfigjson
