apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-amoc-pvc
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-hhk-pvc
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-art-pvc
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-amoc
  namespace: wordpress
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: wp-amoc
  template:
    metadata:
      labels:
        app: wp-amoc
    spec:
      imagePullSecrets:
        - name: registry-secret
      containers:
        - name: wordpress
          image: wordpress:6.8.2
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: mariadb
            - name: WORDPRESS_DEBUG
              value: "0"
            - name: WORDPRESS_DB_USER
              value: wp-amoc
            - name: WORDPRESS_DB_NAME
              value: wp-amoc
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dbusers
                  key: wp-amoc
          volumeMounts:
            - mountPath: /var/www/html
              name: wordpress-data
      volumes:
        - name: wordpress-data
          persistentVolumeClaim:
            claimName: wp-amoc-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: wp-amoc
  namespace: wordpress
spec:
  type: LoadBalancer
  selector:
    app: wp-amoc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-hhk
  namespace: wordpress
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: wp-hhk
  template:
    metadata:
      labels:
        app: wp-hhk
    spec:
      imagePullSecrets:
        - name: registry-secret
      containers:
        - name: wordpress
          image: wordpress:6.8.2
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: mariadb
            - name: WORDPRESS_DB_USER
              value: wp-hhk
            - name: WORDPRESS_DB_NAME
              value: wp-hhk
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dbusers
                  key: wp-hhk
          volumeMounts:
            - mountPath: /var/www/html
              name: wordpress-data
      volumes:
        - name: wordpress-data
          persistentVolumeClaim:
            claimName: wp-hhk-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: wp-hhk
  namespace: wordpress
spec:
  type: LoadBalancer
  selector:
    app: wp-hhk
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-art
  namespace: wordpress
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: wp-art
  template:
    metadata:
      labels:
        app: wp-art
    spec:
      imagePullSecrets:
        - name: registry-secret
      containers:
        - name: wordpress
          image: wordpress:6.8.2
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: mariadb
            - name: WORDPRESS_DB_USER
              value: wp-art
            - name: WORDPRESS_DB_NAME
              value: wp-art
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dbusers
                  key: wp-art
          volumeMounts:
            - mountPath: /var/www/html
              name: wordpress-data
      volumes:
        - name: wordpress-data
          persistentVolumeClaim:
            claimName: wp-art-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: wp-art
  namespace: wordpress
spec:
  type: LoadBalancer
  selector:
    app: wp-art
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
